name: Deploy

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Testing
      run: lein test
    - name: Run check format
      run: lein check-format
    - name: Run check idiomatic
      run: lein check-idiomatic
    - name: Deploy clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: lein deploy clojars
    - name: Notification
      run: |
        curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "${{ secrets.TELEGRAM_CHAT }}", "text": "Tadam core deploy", "disable_notification": true}' https://api.telegram.org/${{ secrets.TELEGRAM_BOT }}/sendMessage
